#inventory = listing machines (aka, what to confiure)
[web]
3.235.30.155

[web:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_ssh_common_args='-o StrictHostKeyChecking=no'


#setting vars that apply to everything in the web group ([web:vars]), these tell Ands how to connect


#ans_user = login as ubuntu user aka ec2 ubuntu default same as ssh command

#ans_ssh_p_k_f is using my private key to auth (same key i ssh with)

#ans_ssh_com_args, is a new cloud specific. ANs doesnt wait to ask if you want to
#connect, no prompt, it auto "yes" for you
